// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8X9EyM9yo5k4QcfLHH5n4fbXA-7PMX7A',
    appId: '1:428554498779:web:gnhs-alumni-web',
    messagingSenderId: '428554498779',
    projectId: 'gnhs-alumni',
    authDomain: 'gnhs-alumni.firebaseapp.com',
    storageBucket: 'gnhs-alumni.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8X9EyM9yo5k4QcfLHH5n4fbXA-7PMX7A',
    appId: '1:428554498779:android:72644349916b81112912fe',
    messagingSenderId: '428554498779',
    projectId: 'gnhs-alumni',
    storageBucket: 'gnhs-alumni.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8X9EyM9yo5k4QcfLHH5n4fbXA-7PMX7A',
    appId: '1:428554498779:ios:gnhs-alumni-ios',
    messagingSenderId: '428554498779',
    projectId: 'gnhs-alumni',
    storageBucket: 'gnhs-alumni.firebasestorage.app',
    iosBundleId: 'com.gnhs.alumni',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8X9EyM9yo5k4QcfLHH5n4fbXA-7PMX7A',
    appId: '1:428554498779:ios:gnhs-alumni-macos',
    messagingSenderId: '428554498779',
    projectId: 'gnhs-alumni',
    storageBucket: 'gnhs-alumni.firebasestorage.app',
    iosBundleId: 'com.gnhs.alumni',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8X9EyM9yo5k4QcfLHH5n4fbXA-7PMX7A',
    appId: '1:428554498779:web:gnhs-alumni-windows',
    messagingSenderId: '428554498779',
    projectId: 'gnhs-alumni',
    authDomain: 'gnhs-alumni.firebaseapp.com',
    storageBucket: 'gnhs-alumni.firebasestorage.app',
  );
}
